package org.vaadin;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Grid;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class AppDesign extends VerticalLayout {
    protected Grid grid;
    protected HorizontalLayout iconDetailsForm;
    protected Label iconHtml;
    protected Label iconName;
    protected Button copyNameButton;
    protected Label iconUrl;
    protected Button copyUrlButton;

    public AppDesign() {
        Design.read(this);
    }
}
